### PR TITLE
Command Binary Interface

### PR DESCRIPTION
**Pull request by fabaff**
This is a MVP for a Command Binary Interface. It's heavily based on `Ping`.

```python
"""Demo for the Command Interface."""
import logging
import shc
import datetime
import json

from shc.interfaces.command import Command
from shc.web import WebServer
from shc.web.widgets import TextDisplay, DisplayButton, ButtonGroup, icon

server = WebServer("localhost", 8080, index_name="index")

index_page = server.page("index", "Command Binary Interface")

# Check if a system service is running
command1 = Command("systemctl is-active sshd.service")
command1_result = shc.Variable(str, "Command result 1").connect(command1)

index_page.add_item(
    TextDisplay(str, "{}", "Command 1").connect(command1).connect(command1_result)
)

# Get random value (1 or 0)
command2 = Command("echo $((RANDOM%2))")

command2_result = shc.Variable(bool, "Command result 2").connect(
    command2, convert=(lambda x: bool(int(x)))
)

index_page.add_item(
    ButtonGroup(
        "Command 2",
        [
            DisplayButton(label=icon("bell outline"), color="teal").connect(
                command2_result
            ),
        ],
    )
)

# Get data from a RESTful API (no error handling!)
command3 = Command("curl http://worldtimeapi.org/api/ip", datetime.timedelta(minutes=5))
command3_result = shc.Variable(str, "Command result 3").connect(
    command3, convert=(lambda x: json.loads(x)["datetime"])
)

index_page.add_item(TextDisplay(str, "{}", "Command 3").connect(command3_result))


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    shc.main()
```

### CODE REVIEW

**Comment by mhthies** [comment]
Hi again,

I feel that this interface should provide a more generic functionality to be merged to the SHC code base. Currently, I cannot think of any program that prints either "1" or "0" to stdout. To make it usable for more different scenarios, I would propose to modify the interface, such that it is `Subscribable[bytes]` or `Subscribable[str]`, publishing the full stdout of the called process (either as raw bytes or decoded with the system default (!) encoding).

Another possibility (maybe another interface class with some shared code) would be publishing the program's exit code as an `int`.

You could still use these interfaces in your example by providing a custom `convert` function when subscribing/connecting the button to your interface:
```python3
DisplayButton(label=icon("bell outline"), color="teal").connect(command, convert=(lambda x: x, lambda x: bool(int(x))))
```
(I used the identity function for the bool → str conversion here, since the type checker expects a callable object, but we don't actually need this function.)

Of course, you can also use the interface just as it is by defining the interface class in your custom SHC application. I actually do this in my private SHC projects, implementing interfaces to our Yamaha sourround receiver and a custom LED controller, which tailored to our specific application and not generic enough to integrate them into the SHC codebase.

**Comment by mhthies** [comment]
An addtional comment on your code example:

You should use an `shc.Variable(bool)` "between" the interface and the `DisplayButton` for caching the current state. The DisplayButton expects to be connected to a `Readable` object to read the current state whenever a new web client connects. Since, your Interface implementation is only *Subscribable*, but not *Readable*, new web clients will only see a loader animation until the interface publishes the next value. Creating a `Variable` that caches the current state and *connecting* both, the Interface and the DisplayButton to it, will resolve this.

**Comment by fabaff** [comment]
> Currently, I cannot think of any program that prints either "1" or "0" to stdout.

Depends on how much Bash foo you want :wink: 

```bash
$ ping -W 1 -c 1 192.168.1.1 > /dev/null 2>&1 && echo 1 || echo 0
```

or only go for the specific information:

```bash
$ cat /proc/sys/net/ipv4/ip_nonlocal_bind
```

On second thought it was indeed very limited as other commands return different information. Like  `active`/`inactive`:

```bash
$ systemctl is-active sshd.service
```

With `convert` one could basically run every command and to do the evaluation later. 

> Of course, you can also use the interface just as it is by defining the interface class in your custom SHC application.

I could but I would prefer to have it upstream. This will avoid that somebody else is re-inventing the wheel while it would be possible to improve the existing "not perfect" or "covering other use cases" Command interface.

> I actually do this in my private SHC projects, implementing interfaces to our Yamaha sourround receiver and a custom LED controller,...

I think that people like me could learn a thing or two from those interfaces.

> Creating a Variable that caches the current state and connecting both, the Interface and the DisplayButton to it, will resolve this.

Thanks for the hint. And, of course, for your feedback.

**Comment by mhthies** [comment]
I've taken your ideas from this PR and modified them a bit before merging:
- I changed the base class from `Subscribable[str]` to `Readable[str]`, such that the command is not called periodically, but instead is called every time the object is being read. You can easily do this perioically, using the `shc.misc.PeriodicReader` (see docstring of `Command` for an example).
- I added the `shell`, `check` and `include_std_err` parameters, allowing to customize the behaviour
- I added the CommandExitCode class, taking up my idea from above to publish the exit code instead of the stdout of the command.

**Pull request merged**
